version: '3'

services:
  anymind:
    container_name: anymind
    build: .
    ports:
      - 80:80
    volumes:
      - ./app:/app
    entrypoint: uvicorn --reload --host 0.0.0.0 --port 80  main:app # Start Uvicorn with live reload
    stdin_open: true
    tty: true
